FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /migrate-to-pg ./cmd/migrate-to-pg

FROM alpine:3
RUN apk add --no-cache ca-certificates
COPY --from=builder /migrate-to-pg /bin/migrate-to-pg
ENTRYPOINT ["/bin/migrate-to-pg"]